import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { MonsterProvider } from "./providers/monster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | TsutomuT",
    default: "TsutomuT",
  },
  description: "Generated by create next app",
};

const navItems = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
  { label: "Monster", href: "/monster" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className={cn(inter.className, "min-h-dvh")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="container h-16 flex items-center border-b justify-between">
            <h1 className="font-bold">Logo</h1>
            <ul className="flex gap-4">
              {navItems.map((item) => (
                // eslint-disable-next-line react/jsx-key
                <li>
                  <Button variant="ghost" asChild>
                    <Link href={item.href}>{item.label}</Link>
                  </Button>
                </li>
              ))}
            </ul>
          </header>
          <MonsterProvider>{children}</MonsterProvider>

          <footer className="container static top-full h-16 flex justify-between items-center border-t">
            <p>&copy; TsutomuT</p>

            <ModeToggle />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
